sudo: required
dist: trusty
env:
  global:
  - CONDA_DEPS="pip pytest numpy pillow pandas requests scipy nltk six tqdm seaborn opencv
    matplotlib pathos tensorflow contextlib2"
  - secure: XwXubMYVa7nTQK2XwJySgtFM/+8xzzaQClSWI76Nik5eqb2yVW4DTJnpeZgp66EvTHEc202bddmleZ6bPw/wWauk+UEjTuRckeocM70rIdSEjzGuDMEKNRmxSQ+5ysf2f7akrog6aUtNjKaEZJIV8RlUWHGLNNAybtTS73tiwcM=
  - secure: OAxWIyFPse0jBXLdS9GzcQgM4d0/lYY9zzAycth0hqOPIrjAzkfUSFz/aGu0ODErwRcOrJPCV8RSaBq5uVCGQ4U7Yl/UKYhS4fkye/CUehmUUDtRxlUIl7pwUznjR8YDHglB9GcGN2FQEz44eLmSWz7JQCKEyqfGEqIHJxb4HmA=
  - secure: NZyKWPNNYP1vAIYAl3yqGNJzAvNkiSgrQZOpxkbDvAXZWaObmeeaUPDoxrG8gs7ypv09+FaHyy7rdhkknl5anmSmA8j8VS3CweU97Wz7J+TLr+S6Gnox4z7Y9hwFI29inAEyIUxPQFafRGOOZbyWt6FBo0O4MvB1FKw9fl8Hcf0=
  - secure: e89Wz4wCZpQSgMZIoZYTKw0dWIy+amP1WSq9Io2V0xyDoH7yC8Wp8kEJSZaxNWQk3Pf13hkq41vu/+KE55oCGLBbCmvdoWcBhw0UOCZywwbeqNapbxC8RP+JtBTPSCJNcN6C3Al0IOoB9xapgcHycjzMw6RekZR2t+daMe4ycxg=
matrix:
  include:
  - os: linux
    env:
    - PYTHON_VERSION=3.5
    - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
  - os: linux
    env:
    - PYTHON_VERSION=2.7
    - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
before_install:
- |
  if [[ -v GOOGLE_APPLICATION_CREDENTIALS ]]; then
  openssl aes-256-cbc -K $encrypted_a0a62c26415d_key -iv $encrypted_a0a62c26415d_iv
  -in pliers/tests/credentials/google.json.enc -out pliers/tests/credentials/google.json -d;
  fi
- sudo add-apt-repository ppa:mc3man/trusty-media -y
- sudo apt-get -qq update
- sudo apt-get install libmp3lame-dev ffmpeg tesseract-ocr graphviz cmake
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- hash -r
- conda info -a
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -y conda
- rm -rf /home/travis/miniconda/envs/test-env
- conda create -q -n test-env python=$PYTHON_VERSION $CONDA_DEPS
- source activate test-env
install:
- sudo apt-get install libboost-python-dev
- pip install --upgrade --ignore-installed setuptools
- pip install python-magic coveralls pytest-cov pysrt xlrd clarifai pytesseract
- pip install moviepy==0.2.2.13
- pip install SpeechRecognition IndicoIo pygraphviz sklearn python-twitter gensim
  google-compute-engine librosa face_recognition google-api-python-client
before_script:
- python -m pliers.support.download
script:
- py.test --pyargs pliers --cov-report term-missing --cov=pliers
after_success:
- coveralls
before_cache:
- conda clean --tarballs --packages --index-cache
cache:
  directories:
  - "$HOME/miniconda"
