sudo: required

env:
  global:
    - CONDA_DEPS="pip pytest numpy pillow pandas requests scipy nltk six"

matrix:
  include:
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda install python=$PYTHON_VERSION $CONDA_DEPS
- sudo apt-get -qq update
- sudo apt-get install tesseract-ocr

install:
- pip install -r requirements.txt
- pip install coveralls pytest-cov pysrt xlrd clarifai pytesseract matplotlib SpeechRecognition

before_script:
  - python -m featurex.support.download

script:
- py.test --pyargs featurex --cov-report term-missing --cov=featurex

after_success:
- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache

cache:
  directories:
    - $HOME/miniconda