sudo: required
dist: trusty
language: python
matrix:
  include:
  - os: linux
    env:
    - PYTHON_VERSION=3.5
    - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    python: 3.5
  - os: linux
    env:
    - PYTHON_VERSION=3.6
    - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    python: 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_a0a62c26415d_key -iv $encrypted_a0a62c26415d_iv
  -in pliers/tests/credentials/google.json.enc -out pliers/tests/credentials/google.json -d || true
- sudo add-apt-repository ppa:mc3man/trusty-media -y
- sudo apt-get -qq update
- sudo apt-get install libmp3lame-dev ffmpeg tesseract-ocr graphviz cmake
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- hash -r
- conda info -a
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -y conda
- rm -rf /home/travis/miniconda/envs/test-env
- conda create -q -n test-env python=$PYTHON_VERSION
- source activate test-env
install:
- sudo apt-get install libboost-python-dev
- pip install --upgrade --ignore-installed setuptools
- pip install -r requirements.txt --upgrade
- pip install -r optional-dependencies.txt --upgrade 
- pip install --upgrade coveralls pytest-cov
- python -m spacy download en_core_web_sm

before_script:
- python -m pliers.support.download
script:
- py.test --pyargs pliers --cov-report term-missing --cov=pliers -m "no requirespayment"
after_success:
- coveralls
before_cache:
- conda clean --tarballs --packages --index-cache
cache:
  pip: true
  directories:
  - "$HOME/miniconda"
